### PR TITLE
[Port] Shitmed

### PR DESCRIPTION
**Pull request by Roudenn**
просто непонятный порт с изменением 6 тысяч строк, ничего интересного
Порт с https://github.com/Simple-Station/Einstein-Engines/pull/1159

### CODE REVIEW

**Comment by gluesniffler** [comment]
Bold. If you're trying to get the tests to pass, I recommend putting your eye on one thing.

- SharedBodySystem.Parts.RemovePartEffect: This is shitcode, and the cause for 90% of the test fails. But I basically placed it at a point where it wouldnt crash the server *for players* due to null references when trying to cycle through the entities via the OnBodyPartRemoved function... However tests do not like it. It should be refactored somehow to be within RecursiveBodyUpdate, as it does something very similar (drop parts recursively), and would save us the work of iterating.

Before I updated to the latest EE master branch I also had issues with BodyPartComponent's auto-generated state, no clue if its still being annoying.

My DMs are open if you'd like more info or something :trollface:

**Comment by trest100** [comment]
> Bold. If you're trying to get the tests to pass, I recommend putting your eye on one thing.
> 
> * SharedBodySystem.Parts.RemovePartEffect: This is shitcode, and the cause for 90% of the test fails. But I basically placed it at a point where it wouldnt crash the server _for players_ due to null references when trying to cycle through the entities via the OnBodyPartRemoved function... However tests do not like it. It should be refactored somehow to be within RecursiveBodyUpdate, as it does something very similar (drop parts recursively), and would save us the work of iterating.
> 
> Before I updated to the latest EE master branch I also had issues with BodyPartComponent's auto-generated state, no clue if its still being annoying.
> 
> My DMs are open if you'd like more info or something :trollface:

hi, we have almost figured out the tests and rewrote part of your system, now it is more optimized, today we will test on the server
We also have our own developments on the simulation of the circulatory and nervous systems, we will try to integrate them. Thank you again for making the dream of thousands of people come true!

**Comment by trest100** [comment]
> Bold. If you're trying to get the tests to pass, I recommend putting your eye on one thing.
> 
> * SharedBodySystem.Parts.RemovePartEffect: This is shitcode, and the cause for 90% of the test fails. But I basically placed it at a point where it wouldnt crash the server _for players_ due to null references when trying to cycle through the entities via the OnBodyPartRemoved function... However tests do not like it. It should be refactored somehow to be within RecursiveBodyUpdate, as it does something very similar (drop parts recursively), and would save us the work of iterating.
> 
> Before I updated to the latest EE master branch I also had issues with BodyPartComponent's auto-generated state, no clue if its still being annoying.
> 
> My DMs are open if you'd like more info or something :trollface:

^~^

**Comment by gluesniffler** [comment]
Thank you for the help! I'll be checking out the changes and porting them to upstream after testing em myself. Please be sure to report any bugs or weirdness.

**Pull request merged**
